### ISSUE TITLE
Use SimpleUrlEncodedValuePairs from http-client-essentials-suite

### ISSUE THREAD

**Issue by lemonboston** [dmfs/oauth2-essentials#14]
After https://github.com/dmfs/http-client-essentials-suite/issues/25 is completed and released, we can use that class and remove `StructuredStringFragment` from this library.

**Comment by dmfs** [comment]
This is ready to move on. Note that the class is called `UrlFormEncodedKeyValues` now.

**Comment by dmfs** [comment]
Done in f24c17cf5ee6918a3c61d144259011d56f0a37eb.
