### ISSUE TITLE
Test OAuth2 providers

### ISSUE THREAD

**Issue by dmfs** [dmfs/oauth2-essentials#3]
We should have a test suite to test the known provider configurations. How can we do that without publishing our client credentials?

**Comment by dmfs** [comment]
@lemonboston any idea regarding the credentials issue? How can we test the providers without publishing our credentials?

**Comment by lemonboston** [comment]
From a first look, I found these:

We could add the credentials to a properties file that is git ignored
http://stackoverflow.com/questions/12749225
(first answer is not valid any more according to the 2nd one)

For Travis we would need to add the value in encrypted form to the travis.yml
http://stackoverflow.com/questions/9338428/
I am not sure of the security of the public key involved in decryption though..
Also, this would mean a different build locally and on Travis. (Maybe they could be unified somehow with using system variables, not sure.)

So I don't know how properly you would like it to be set up. I guess minimally we could have a gradle-local.properties git ignored with the credentials (one answer suggest this plugin for that:
https://github.com/stevesaliman/gradle-properties-plugin)
And either set it up to be a system property (they say some prefix does that automatically) and access it with System.getProperty() from code or 'convert' it to BuildConfig value in gradle and access it through the generated class. Although, compilation could fail if it is not present, so probably we would need default values in gradle.properties that are overriden in gradle-local.properties. And maybe a separate boolean besides the credentials to indicate if they are valid to use or not. 

We could put those tests permanently to @Ignore and enable ad-hoc locally, or make them run automatically when valid credentials are present. One way for that could be to create separate test source set to control this, but I think this one might be better:
http://stackoverflow.com/questions/1689242/conditionally-ignoring-tests-in-junit-4
http://junit.sourceforge.net/javadoc/org/junit/Assume.html#assumeTrue(boolean)
So we would add the condition in code to ignore the test based on that boolean.

It was just a quick research, so I am not sure if I miss any issue with this approach or there would be simpler or better ones. Let me know if you would like me to spend more time on it, maybe set it up.

**Comment by dmfs** [comment]
The first option works for executing the tests locally, that's basically what I do with the Sonatype credentials. The question is how do we get the credentials into the unit tests where we need them? BuildConfig to the rescue? I guess we could generate a BuildConfig that's test specific and falls back to empty values if no passwords are present (so the build wouldn't fail on travis).

That raises the question, do we want the tests against existing OAuth2 providers to run automatically for every build? I think that's probably not necessary.

Now the other question is: how do we run an interactive Grant in an automated test :-|
I guess that's where this idea is probably going to fail :-(

Afaik Google doesn't provide dummy users that always authenticate or decline the request.

**Comment by lemonboston** [comment]
One more option occurred to me regarding how to handle this config values in code: to use build type/flavor and have multiple versions of a, let's say, TestConfig class that contains the values as constants. 

So with this I see 3 ways, although not totally sure about any of them, would need to actually try them:
1. gradle properties entry with _systemProp_ prefix that is converted to Java system property by gradle and could be accessed with System.getProperty() from code. Default, empty values in gradle.properties under VCS, local valid values in gradle-local.properties
2. simirarily to 1. but without _systemProp_ prefix, and use buildConfig plugin to 'convert' the properties values to BuildConfig fields
3. a separate build variant for these tests, a TestConfig class would have a separate version for the variant , which would not be under version control (that build variant could only be built locally)

I see that it can be problematic to test with real users and providers..   and I can see that it's probably not a good idea to make it part of the build, but could we use them just ad-hoc locally? Not sure what flows and scenarios you would like to test, I am just a little familiar with OAuth2 flows. I can only think now of a successful authorization with good password and a failed one with invalid password or username. I assume there are probably more :) But could these two ones for example be run against a real production provider with our real users from time to time?

I don't know of any dummy/test oauth2 facilities, but I just searched "test google oauth2" and this came up [OAuth 2.0 Playground - Google Developers](https://developers.google.com/oauthplayground/)

**Comment by lemonboston** [comment]
Ok, I just realized that if we just run those tests ad-hoc, then there is of course no need for any automatic credentials reading mechanism. We can just add them to the code directly, in a constant value possibly.

**Comment by dmfs** [comment]
I think the main issue is that the most common/important grant types are interactive and require a webview or browser. We probably could run the test with some UI automation (test-)tool but I think at present it's not worth the effort.
I guess for now it's sufficient if our code is properly unit-tested. I'll close this one. We'll open a new issue if we decide to do this later on.
