### ISSUE TITLE
OAuth2AccessToken#scope() returns requested, not the issued scope

### ISSUE THREAD

**Issue by chludwig-haufe** [dmfs/oauth2-essentials#36]
Hi,

an "_authorization server MAY fully or partially ignore the scope requested by the client_" [[RFC6749, Sect. 3.3](https://tools.ietf.org/html/rfc6749#section-3.3)]. In the authorization server's access token response, the scope field is "_OPTIONAL, if identical to the scope requested by the client; otherwise, REQUIRED_" [[RFC6749, Sect. 5.1](https://tools.ietf.org/html/rfc6749#section-5.1)].

I have a client that obtains an access token using the client credentials flow, using oauth-essentials 0.8. The scope issued by the authorization server is in fact different from the requested scope. 

With the debugger, I can see the issued scope in the field `JsonAccessToken#mTokenresponse`. However, if I try to inspect the scope programatically by calling `OAuth2AccessToken#scope()`, I get the value of the field `JsonAccessToken#mScope` which is passed in (via `TokenResponseHandler` from `ClientCredentialsTokenRequest`.

Is this a bug or did I miss something?

Cheers,
Christoph

**Comment by dmfs** [comment]
Looks like a bug indeed. I'll take care of this.

**Comment by dmfs** [comment]
#37 will fix this. It should be released as 0.8.1 by tomorrow afternoon.

**Comment by chludwig-haufe** [comment]
Great, thanks!

**Comment by dmfs** [comment]
Fixed in 0.8.1
