### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by gianx89** [dmfs/oauth2-essentials#61]
When doing this:

OAuth2AccessToken token = new ClientCredentialsGrant(client, scope).accessToken(executor);

I get:

> java.lang.IncompatibleClassChangeError
> 	at org.dmfs.iterators.decorators.Filtered.moveToNext(Filtered.java:88)
> 	at org.dmfs.iterators.decorators.Filtered.<init>(Filtered.java:58)
> 	at org.dmfs.httpessentials.types.StringMediaType.parameters(StringMediaType.java:76)
> 	at org.dmfs.httpessentials.types.StringMediaType.firstParameter(StringMediaType.java:63)
> 	at org.dmfs.httpessentials.types.StringMediaType.charset(StringMediaType.java:119)
> 	at org.dmfs.httpessentials.responsehandlers.StringResponseHandler.handleResponse(StringResponseHandler.java:88)
> 	at org.dmfs.oauth2.client.http.responsehandlers.TokenErrorResponseHandler.handleResponse(TokenErrorResponseHandler.java:60)
> 	at org.dmfs.oauth2.client.http.responsehandlers.TokenErrorResponseHandler.handleResponse(TokenErrorResponseHandler.java:39)
> 	at org.dmfs.httpessentials.httpurlconnection.PlainHttpUrlConnectionExecutor.execute(PlainHttpUrlConnectionExecutor.java:78)
> 	at org.dmfs.httpessentials.executors.common.decorators.BottomBranded.execute(BottomBranded.java:54)
> 	at org.dmfs.httpessentials.executors.common.decorators.BottomBranded.execute(BottomBranded.java:54)
> 	at org.dmfs.httpessentials.httpurlconnection.HttpUrlConnectionExecutor.execute(HttpUrlConnectionExecutor.java:67)
> 	at org.dmfs.httpessentials.executors.useragent.Branded.execute(Branded.java:53)
> 	at org.dmfs.oauth2.client.BasicOAuth2AuthorizationProvider.accessToken(BasicOAuth2AuthorizationProvider.java:55)
> 	at org.dmfs.oauth2.client.BasicOAuth2Client.accessToken(BasicOAuth2Client.java:63)
> 	at org.dmfs.oauth2.client.grants.ClientCredentialsGrant.accessToken(ClientCredentialsGrant.java:60)
> 	at it.corvallis.multitrace.service.web.WebService.registerUser(WebService.java:248)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
> 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:252)
> 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
> 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at it.corvallis.jwolf.web.servlet.JWCorsFilter.doFilter(JWCorsFilter.java:42)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)
> 

I'm using as dependencies:

```
<dependency org="org.dmfs" name="oauth2-essentials" rev="0.12"/>
<dependency org="org.dmfs" name="httpurlconnection-executor" rev="0.17"/>
```

**Comment by dmfs** [comment]
I can't spot anything wrong in the code. All dependencies seem to match.
I've just tried this code (using the same dependency versions):
```
OAuth2AccessToken token = new ClientCredentialsGrant(
  new BasicOAuth2Client(
    new GoogleAuthorizationProvider(),
    new BasicOAuth2ClientCredentials("x", "y"),
    new LazyUri(new Precoded("http://localhost:123"))),
  new StringScope("scope")).accessToken(new HttpUrlConnectionExecutor());
```
It fails with an error (primarily because Google doesn't support ClientCredentialsGrant), but it passes line 60 of `TokenErrorResponseHandler.java` which it doesn't in your case.

Have you tried a clean build?

**Comment by umjammer** [comment]
i’ve got the same error.

`oauth2-essentials:0.12` depends on `jems:1.18`.

when i changed `jems` version to `1.23` (current newest version), there is no error.

i think `jems` version for `oauth2-essentials` might be wrong, right?

**Comment by dmfs** [comment]
@umjammer that's an interesting finding, thx. I'll publish a new release with updated dependencies.

**Comment by dmfs** [comment]
please check if oauth-essentials 0.13 along with http-client-essentials 0.18 fixes this issue.
